- name: Restart mariadb
  ansible.builtin.service:
    name: mariadb
    state: restarted
  become: true
  
- name: Create WordPress database
  ansible.builtin.mysql_db: 
    name: "{{ wp_db_name }}"
    state: present
    login_user: root
    login_password: "{{ root_pass }}"
  become: true
  tags: db

- name: Create WordPress database user
  ansible.builtin.mysql_user: 
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: "%"
    state: present
    login_user: root               
    login_password: "{{ root_pass }}"
    column_case_sensitive: false
  become: true
