- name: Install necessary packages for MariaDB repo for ubuntu 20
  ansible.builtin.apt:
    name:
      - software-properties-common
      - dirmngr
      - apt-transport-https
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == "Debian" and ansible_distribution_release == "focal"
  become: true
  tags: repo20

- name: Install necessary packages for MariaDB repo for ubuntu 22
  ansible.builtin.apt:
    name:
      - software-properties-common
      - gnupg2
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == "Debian" and ansible_distribution_release == "jammy"
  become: true
  tags: repo22

- name: Install the official MariaDB repository key
  ansible.builtin.apt_key:
    url: "https://mariadb.org/mariadb_release_signing_key.asc"
    state: present
  become: true
  tags: key

- name: Setup mariadb repository sourcelist entry for ubuntu 20
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,arm64,ppc64el] {{ install_mariadb_ubun20 }}ubuntu {{ ansible_distribution_release }} main"
    filename: mariadb
    state: present
  when: ansible_facts['os_family'] == "Debian" and ansible_distribution_release == "focal"
  become: true
  tags: source20

- name: Setup mariadb repository sourcelist entry for ubuntu 22
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,arm64,ppc64el] {{ install_mariadb_ubun22 }}ubuntu {{ ansible_distribution_release }} main"
    filename: mariadb
    state: present
  when: ansible_facts['os_family'] == "Debian" and ansible_distribution_release == "jammy"
  become: true
  tags: source22