- import_tasks: install_from_repo.yml
  when: install_mariadb_repos | bool

- name: Determine required MariaDB Python libraries
  set_fact:
    mariadb_python_package: "{% if 'python3' in ansible_python_interpreter|default('') %}python3-pymysql{% else %}python-pymysql{% endif %}"

- name: Ensure MariaDB Python libraries are installed
  ansible.builtin.apt:
    name: "{{ python_package }}"
    state: present
  become: true
  tags: lib 
  
- name: Install MariaDB packages
  ansible.builtin.apt:
    name:
      - mariadb-common
      - mariadb-server
      - mariadb-client    
    update_cache: true
    state: present
  become: true


- name: Add .my.cnf to root directory
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /root/.my.cnf
  become: true
  tags: my1

- name: Add my.cnf to 50-server.cnf directory
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
  become: true
  tags: my2

- name: Restart mariadb
  ansible.builtin.service:
    name: mariadb
    state: restarted
  become: true