- name: Stop apache2 to avoid error with nginx 
  ansible.builtin.service:
    name: apache2.service
    state: stopped
  become: true

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  become: true
  
- name: Copy nginx config file
  ansible.builtin.template:
    src: default.j2
    dest: "{{ nginx_serverblocks }}"
  become: true

