- name: Check if SSL certificate already exists
  ansible.builtin.stat:
    path: "{{ ssl_file }}"
  register: cert_state
  tags: sslcheck

- name: Copy ssl certificate to the remote server
  ansible.builtin.copy:
    src:  "{{ source_directory }}"
    dest: "{{ file_directory }}"
    owner: admin
    group: admin
    mode: "0600"
  when: not cert_state.stat.exists
  become: true
  tags: sslcheck




